name: CI-CD Lacrei Saude

on:
  push:
    branches:
      - main
      - develop

jobs:
  ci-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar Lint
        run: npm run lint

      - name: Rodar Testes Unitários
        run: npm test

  deploy:
    needs: ci-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Definir IP do Ambiente
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TARGET_IP=${{ secrets.PRODUCTION_IP }}" >> $GITHUB_ENV
          else
            echo "TARGET_IP=${{ secrets.STAGING_IP }}" >> $GITHUB_ENV
          fi

      - name: Copiar arquivos de config para a AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.TARGET_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,nginx/default.conf"
          target: "~/app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.TARGET_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            # Exporta a tag do commit para o docker-compose usar a imagem exata
            export IMAGE_TAG=${{ github.sha }}
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/lacrei-api:${{ github.sha }}
            
            docker-compose down
            docker-compose up -d